baseURL = 'https://jatuzprzypadku.pl/'

languageCode = 'pl'
defaultContentLanguage = 'pl'

title = 'Ja tu z przypadku!'
theme = "base"
enableRobotsTXT = true

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 20 # Configure how long the post summary should be on the homepage.


# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "/about/"
    weight = 1 # used to sort menu items


[taxonomies]
    tag = "tags"

[author]
    name = "klowkis"

[params]
    description = "Blog o psychologi, postrzeganiu swiata, i o tym co się może przydarzyć"
    twitter = "https://twitter.com/jatuzprzypadku"
    instagram = "https://instagram.com/ja_tu_z_przypadku"
    showReadMore = true

