baseURL = 'https://www.jatuzprzypadku.pl/'

languageCode = 'pl'
defaultContentLanguage = 'pl'

title = 'Ja tu z przypadku!'
theme = "base"
enableRobotsTXT = true

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 20 # Configure how long the post summary should be on the homepage.


# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""



# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "/about/"
    weight = 1 # used to sort menu items

[taxonomies]
    tag = "tags"

[author]
    name = "klowkis"

[params]
    description = "Tutaj trzeba dodać krótki opis bloga"
    twitter = "https://twitter.com/SMuminka"
    instagram = "https://instagram.com/"
    showReadMore = true

