baseURL = 'https://www.jatuzprzypadku.pl/'

languageCode = 'pl'
title = 'Ja tu z przypadku'
theme = "noteworthy"
enableRobotsTXT = true

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "/about/"
    weight = 1 # used to sort menu items

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[taxonomies]
    tag = "tags"

[author]
    name = "klowkis"

[params]
    description = "Tutaj trzeba dodać krótki opis bloga"
    twitter = "https://twitter.com/SMuminka"
